config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  
  resources :posts do
  	resources :likes
  	resources :comments
  end
  
  resources :users, only: [:show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post
  
end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :user
  belongs_to :post
  
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :likes
  has_many :comments
  has_attached_file :photo,
    :styles => {:small => "150x150", :large => "600x600"},
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/aws.yml";

  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  validates :title, :description, :photo, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	  validates :username, uniqueness: true

  has_many :posts
  has_many :comments
  has_many :likes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:account_update).push(:username)
  	devise_parameter_sanitizer.for(:sign_up).push(:username)
  	devise_parameter_sanitizer.for(:sign_in).push(:username)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@comment = Comment.new
	end

	def create
		@user = current_user
		@comment = @user.comments.create(comment_params)

		if current_user && @comment.save
			@post = Post.find(@comment.post_id)
			respond_to do |format|
				format.js
			end
		end
	end

	def edit
		@comment = Comment.find(params[:id])
		@post = Post.find(@comment.post_id)
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
		@comment.update_attributes(comment_params)
		if current_user && @comment.save
			respond_to do |format|
				format.js
			end
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
	end

	private

	def comment_params
		params.require(:comment).permit(:content, :post_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@post = Post.all
	end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def new
		@like = Like.new
	end

	def create
		@user = current_user
		@like = @user.likes.create(like_params)

		if current_user && @like.save
			@post = Post.find(@like.post_id)
			respond_to do |format|
			  format.js {render inline: "location.reload();" }
			end
		end
	end

	def destroy
		@like = current_user.likes.find_by_post_id(params[:post_id])
		@like.destroy
			respond_to do |format|
			  format.js {render inline: "location.reload();" }
			end
	end

	private

	def like_params
		params.require(:like).permit(:post_id)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.update_attributes(user_id: current_user.id)
		if @post.save
			redirect_to @post
		else
			render :new
		end
	end

	def show
		@post = Post.find(params[:id])
		@post.viewcount += 1
		@post.save
		@comment = Comment.new
		if user_signed_in?
			unless @like = current_user.likes.find_by_post_id(@post.id)
				@like = Like.new
			end
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post = Post.update!(post_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :description, :photo)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def show
		@user = User.find(params[:id])
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comment-<%=comm.id %> comments">
  <div class="comment_content comment-des">
  	<div class="comment-by">
  		<strong><%= link_to comm.user.username, user_path(comm.user) %></strong>
  	</div>
  	<p>
    	<%= comm.content %>
  	</p>
  </div>
  <% if comm.user == current_user %>
	  <%= link_to "Edit", edit_post_comment_path(post, comm), remote: true %>
	  <%= link_to "Delete", post_comment_path(post, comm), :method => :delete, remote: true %>
  <% end %>
  <br>
</div>

app/views/comments/_form.html.erb
<h3>Leave a Comment</h3>
<div id="contact-form">
  <%= form_for [post, comment], remote: true do |f| %>
  	<div class="field">
    	<%= f.text_area :content, :placeholder => 'Comment', :class => 'comment text textarea' %>
  	</div>
  	<div class="field">
  		<%= f.hidden_field :post_id, :value => post.id %>
  	</div>
  	<div class="field">
    	<%= f.submit "Comment", :id => 'send'%>
  	</div>
  <% end %>
</div>

app/views/comments/create.js.erb
$('.postcomments').append(
		'<%= j render "comment", post: @post, comm: @comment %>')
$('#comment_content').val('');

app/views/comments/destroy.js.erb
$(".comment-<%=@comment.id %>").remove()

app/views/comments/edit.js.erb
$(".comment-<%=@comment.id %> .comment_content").html("<%= j render 'form', post: @post, comment: @comment %>")

app/views/comments/update.js.erb
$(".comment-<%=@comment.id %> .comment_content").html('<%= j @comment.content %>')

app/views/home/index.html.erb
<div id="wall" class="row-fluid">
  <% @post.each do |post| %>
    <div class="span3 item">
      <div class="picture">
        <%= link_to image_tag(post.photo.url(:small)), post_path(post), class: "image" %>
          <div class="meta">
              <%= image_tag "eye97.png", class: "icons" %> <%= post.viewcount %>
              <%= image_tag "like47.png", class: "icons" %> <%= post.likes.length %>
              <%= image_tag "speech95.png", class: "icons" %> <%= post.comments.length %>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div id="under-footer">
  <div class="container">
    <div class="row-fluid">
      <div class="span2">
        <div id="under-footer-logo">
          <%= link_to "Fashion", root_path, class: "brand" %>
        </div>
      </div>
      <div class="span9">
        <div id="under-footer-copyright">
          &copy; 2014 <a href="#" alt="Milpitas Trio">MilpitasTrioLabs</a>
        </div>
      </div>
    </div>
  </div>  
</div>

app/views/layouts/_navbar.html.erb
<header>
  <div class="container">
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="nav-collapse collapse">
          <ul class="nav">
            <% if user_signed_in? %>
              <li><%= link_to "Fashion", root_path, class: "brand" %></li>
              <li><%= link_to "Create Post", new_post_path %></li>
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
            <% else %>
              <li><%= link_to "Fashion", root_path, class: "brand" %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- start: Meta -->
  <meta charset="utf-8">
  <title>Fashion</title> 
  <meta name="description" content="Tabula Bootstrap Theme"/>
  <meta name="keywords" content="Template, Theme, web, html5, css3, Bootstrap, pin, wall, responsive, fluid, retina" />
  <meta name="author" content="Łukasz Holeczek from creativeLabs"/>
  <!-- end: Meta -->
  
  <!-- start: Mobile Specific -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!-- end: Mobile Specific -->
  
  <!-- start: Facebook Open Graph -->
  <meta property="og:title" content=""/>
  <meta property="og:description" content=""/>
  <meta property="og:type" content=""/>
  <meta property="og:url" content=""/>
  <meta property="og:image" content=""/>
  <!-- end: Facebook Open Graph -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>

<%= render "layouts/navbar" %>
<%= yield %>
<%= render "layouts/footer" %>


</body>
</html>

app/views/likes/_form.html.erb
<div>
	<% if current_user.likes.find_by_post_id(post.id) %>
	  <%= form_for [post, like], :method => :delete, remote: true do |f| %>
	  <%= f.submit "Unlike" %>
	  <% end %>
	<% else %>
	  <%= form_for [post, like], remote: true do |f| %>
	  	<%= f.hidden_field :post_id, :value => post.id %>
	    <%= f.submit "Like" %>
	  <% end %>
  <% end %>
</div>

app/views/likes/create.js.erb
$('.new_like').remove(

app/views/posts/_form.html.erb
 <%= form_for @post do |f| %>
  <%= f.text_field :title, placeholder: "Title" %>
  <br>
  <%= f.text_area :description, placeholder: "Description" %>
  <br>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
	<div id="wrapper">
		<div class="posts span 8">
			<div class="post first last">

				<div class="post-img picture">
					<%= image_tag @post.photo.url(:large) %>
				</div>
				<div class="info">

					<span class="post-icon standard"><i class="icon-camera-retro"></i></span>
				</div>

				<div class="post-content">
					<div class="post-title">
						<h2><%= @post.title %></h2>
					</div>

					<div class="post-meta">
						<span><i class="icon-user"></i>By <%= @post.user.username %></span> 
						<span><i class="icon-comments-alt"></i>Likes: <%= @post.likes.length %></span>
					</div>

					<div class="post-description">
						<p><%= @post.description %></p>
					</div>
				</div>
			</div>

			<h3>Comments</h3>
			<div class="comments-sec">
				<ol class="commentlist postcomments">
					<% @post.comments.each do |comment| %>
						<li><%= render "comments/comment", post: @post, comm: comment %></li>
					<% end %>
				</ol>
			</div>
			<% if current_user == @post.user %>
	<div>
		<%= link_to "Edit", edit_post_path(@post) %>
		<%= link_to "Delete", post_path(@post), method: :delete %>
	</div>
<% end %>


<% if user_signed_in? %>
  <%= render "likes/form", post: @post, like: @like %>
	<%= render "comments/form", post: @post, comment: @comment %>
<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>

<h2>Posts:</h2>
<% @user.posts.each do |post| %>
	<div>
		<%= link_to image_tag(post.photo.url(:small)), post_path(post) %>
	</div>
<% end %>

<h2>Likes:</h2>
<% @user.likes.each do |like| %>
	<div>
		<%= link_to image_tag(like.post.photo.url(:small)), post_path(like.post) %>
	</div>
<% end %>

<h2>Comments:</h2>
<% @user.comments.each do |comment| %>
	<div>
		<%= link_to comment.content, post_path(comment.post) %>
	</div>
<% end %>